services:
  orpheus:
    build: .
    ports:
      - "5000:5000"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  orpheus-cpu:
    build: .
    ports:
      - "5000:5000"
